[package]
name = "sparse_vector"
version = "0.1.0"
edition = "2024"

[dependencies]
only_one = { git = "https://github.com/nossie531/only_one" }
pstd = "1"

[dev-dependencies]
permute = "0.2"
rand = "0.9"
rand_pcg = "0.9"
upget = "0.2"
test_panic = "0.4"
