[package]
name = "sparse_vector"
version = "0.1.0"
edition = "2024"

[dependencies]
pstd = "1"
nameof = "1"
only_one = { git = "https://github.com/nossie531/only_one" }

[dev-dependencies]
rand = "0.9"
rand_pcg = "0.9"
test_panic = "0.4"
